[[constraint]]
  branch = "master"
  name = "github.com/eknkc/amber"

[[constraint]]
  name = "github.com/russross/blackfriday"
  version = "1.5"

[[constraint]]
  name = "github.com/yosssi/gcss"
  version = "0.1.0"

[[constraint]]
  branch = "v2"
  name = "gopkg.in/yaml.v2"
